# Entry point for provisioning specification. First, groups by host
# platform and then chooses a provisioning role based on host key. A
# "role" here is a set of tasks to be performed in order, just like a
# bash script, but (i) allows you to easily control logging level,
# (ii) stores some state about its run so it can be safely run and
# then repeated, (iii) permits easy dependency ordering of tasks:
# i.e., all the reliability issues that are a pain with bash.
#
# If looking to make changes and finding this unfamiliar, check out
# this example: https://gist.github.com/marktheunissen/2979474 .

- hosts: all
  tasks:
     - group_by: key={{ ansible_distribution }}

- name: provision piksi development dependencies for Ubuntu
  hosts: Ubuntu
  gather_facts: false
  roles:
    - common_ubuntu

- name: provision piksi development dependencies for Debian
  hosts: Debian
  gather_facts: false
  roles:
    - common_ubuntu

- name: provision piksi development dependencies for OS X
  hosts: MacOSX
  gather_facts: false
  roles:
    - common_osx
