BINARY = usart_dma_test

OBJS = usart_dma_test.o \
       ../../src/error.o \
       ../../src/settings.o \
       ../../src/hw/leds.o \
       ../../src/hw/usart.o \
       ../../src/hw/usart_tx.o \
       ../../src/hw/usart_rx.o \

CFLAGS += -I../../src/

SWIFTNAV_ROOT ?= ../..

include ../../stm32/Makefile.include

