BINARY = usart_dma_test

OBJS = usart_dma_test.o \
       ../../src/debug.o \
       ../../src/hw/leds.o \
       ../../src/hw/usart.o \

CFLAGS += -I../../src/

SWIFTNAV_ROOT ?= ../..

include ../../stm32/Makefile.include

