BINARY = luftboot

OBJS = luftboot.o \
       ../src/debug.o \
       ../src/error.o \
       ../src/hw/usart.o \
       ../src/hw/usart_rx.o \
       ../src/hw/usart_tx.o \
       ../src/hw/leds.o \
       ../src/hw/stm_flash.o \

CFLAGS += -I../src/

SWIFTNAV_ROOT ?= ..

include Makefile.include
