-include $(SWIFTNAV_ROOT)/ext/*/Makefile.include

CSRC += $(SWIFTNAV_ROOT)/ext/ext.c

$(SWIFTNAV_ROOT)/ext/ext.c: FORCE
	@echo "Generating ext.c"
	-@rm $@
	@for f in $(EXT_SETUP); do \
		echo "extern void $$f(void);" >> $@; \
	done
	@echo "void ext_setup(void) {" >> $@
	@for f in $(EXT_SETUP); do \
		echo "\t$$f();" >> $@; \
	done
	@echo "}" >> $@

FORCE:

