BINARY = swiftnav-firmware

OBJS = main.o \
       debug.o \
			 m25_flash.o \
			 max2769.o \
			 swift_nap.o \
       board/leds.o \
       board/exti.o \
       board/spi.o

include ../stm32/Makefile.include

